name: Main Branch - Preview and Release
on:
    push:
        branches:
         - main

jobs:
    build-or-update:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
         - name: Checkout repository
           uses: actions/checkout@v4
           with:
            fetch-depth: 0
        
         - name: Setup Node
           uses: actions/setup-node@v4
           with:
            node-version: 22
        
         - name: Setup Expo and EAS
           uses: expo/expo-github-action@v8
           with:
            token: ${{ secrets.EXPO_TOKEN }}
            eas-version: latest

         - name: Install dependancies
           run: npm ci

         - name: Calculate Native Fingerprint
           id: fingerprint
           run: |
            HASH=$(npx @expo/fingerprint . | jq -r .hash)
            echo "hash=$HASH" >> $GITHUB_OUTPUT

         - name: Check for Existing Release
           id: check_release
           env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           run: |
            if gh release view v0.1.0-alpha-${{ steps.fingerprint.outputs.hash }} &>dev/null; then
                echo "exists=true" >> $GITHUB_OUTPUT
            else
                echo "exists=false" >> $GITHUB_OUTPUT
            fi

         - name: Publish OTA Update (No native changes)
           if: steps.check_release.outputs.exists == 'true'
           run: |
            eas update --branch preview --platform android --message "Automated update for commit ${{ github.sha }}"
        
         - name: Build Android Preview
           if: steps.check_release.outputs.exists != 'true'
           run: |
            eas build --platform android --profile preview --non-interactive
        
         - name: Download Build Artifact
           if: steps.check_release.outputs.exists != 'true'
           run: |
            eas build:download --platform android --fingerprint ${{ steps.fingerprint.outputs.hash }} --non-interactive

         - name: Create Github Pre-release
           if: steps.check_release.outputs.exists != 'true'
           env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           run: |
            gh release create v0.1.0-alpha-${{ steps.fingerprint.outputs.hash }} \
                --target main \
                --prerelease \
                --title "Preview Build (${{ steps.fingerprint.outputs.hash }})" \
                --generate-notes \
                *.apk
           